# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt_NetSignalInfofExportTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NetSignalInfoExportTool(object):
    def setupUi(self, NetSignalInfoExportTool):
        NetSignalInfoExportTool.setObjectName("NetSignalInfoExportTool")
        NetSignalInfoExportTool.resize(1050, 716)
        NetSignalInfoExportTool.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(NetSignalInfoExportTool)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_DatabaseFileInput = QtWidgets.QLabel(self.centralwidget)
        self.Label_DatabaseFileInput.setMinimumSize(QtCore.QSize(200, 30))
        self.Label_DatabaseFileInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.Label_DatabaseFileInput.setFont(font)
        self.Label_DatabaseFileInput.setObjectName("Label_DatabaseFileInput")
        self.horizontalLayout.addWidget(self.Label_DatabaseFileInput)
        self.lineEdit_DatabaseFileInput = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DatabaseFileInput.sizePolicy().hasHeightForWidth())
        self.lineEdit_DatabaseFileInput.setSizePolicy(sizePolicy)
        self.lineEdit_DatabaseFileInput.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DatabaseFileInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_DatabaseFileInput.setReadOnly(True)
        self.lineEdit_DatabaseFileInput.setObjectName("lineEdit_DatabaseFileInput")
        self.horizontalLayout.addWidget(self.lineEdit_DatabaseFileInput)
        self.pushButton_DatabaseFileInputSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DatabaseFileInputSelect.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_DatabaseFileInputSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.pushButton_DatabaseFileInputSelect.setFont(font)
        self.pushButton_DatabaseFileInputSelect.setObjectName("pushButton_DatabaseFileInputSelect")
        self.horizontalLayout.addWidget(self.pushButton_DatabaseFileInputSelect)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label_OutputFolder = QtWidgets.QLabel(self.centralwidget)
        self.Label_OutputFolder.setMinimumSize(QtCore.QSize(200, 30))
        self.Label_OutputFolder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.Label_OutputFolder.setFont(font)
        self.Label_OutputFolder.setObjectName("Label_OutputFolder")
        self.horizontalLayout_2.addWidget(self.Label_OutputFolder)
        self.lineEdit_OutputFolder = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_OutputFolder.sizePolicy().hasHeightForWidth())
        self.lineEdit_OutputFolder.setSizePolicy(sizePolicy)
        self.lineEdit_OutputFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_OutputFolder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_OutputFolder.setReadOnly(True)
        self.lineEdit_OutputFolder.setObjectName("lineEdit_OutputFolder")
        self.horizontalLayout_2.addWidget(self.lineEdit_OutputFolder)
        self.pushButton_OutputFolderSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OutputFolderSelect.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_OutputFolderSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.pushButton_OutputFolderSelect.setFont(font)
        self.pushButton_OutputFolderSelect.setObjectName("pushButton_OutputFolderSelect")
        self.horizontalLayout_2.addWidget(self.pushButton_OutputFolderSelect)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.Label__ToolTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label__ToolTitle.sizePolicy().hasHeightForWidth())
        self.Label__ToolTitle.setSizePolicy(sizePolicy)
        self.Label__ToolTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(24)
        self.Label__ToolTitle.setFont(font)
        self.Label__ToolTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Label__ToolTitle.setObjectName("Label__ToolTitle")
        self.gridLayout.addWidget(self.Label__ToolTitle, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_GenerateSignalInfoTable = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_GenerateSignalInfoTable.sizePolicy().hasHeightForWidth())
        self.pushButton_GenerateSignalInfoTable.setSizePolicy(sizePolicy)
        self.pushButton_GenerateSignalInfoTable.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.pushButton_GenerateSignalInfoTable.setFont(font)
        self.pushButton_GenerateSignalInfoTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_GenerateSignalInfoTable.setObjectName("pushButton_GenerateSignalInfoTable")
        self.gridLayout.addWidget(self.pushButton_GenerateSignalInfoTable, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        NetSignalInfoExportTool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NetSignalInfoExportTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        NetSignalInfoExportTool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NetSignalInfoExportTool)
        self.statusbar.setObjectName("statusbar")
        NetSignalInfoExportTool.setStatusBar(self.statusbar)

        self.retranslateUi(NetSignalInfoExportTool)
        self.pushButton_DatabaseFileInputSelect.clicked.connect(self.Label_DatabaseFileInput.update)
        self.pushButton_OutputFolderSelect.clicked.connect(self.Label_OutputFolder.update)
        self.pushButton_GenerateSignalInfoTable.clicked.connect(self.pushButton_GenerateSignalInfoTable.setFocus)
        QtCore.QMetaObject.connectSlotsByName(NetSignalInfoExportTool)

    def retranslateUi(self, NetSignalInfoExportTool):
        _translate = QtCore.QCoreApplication.translate
        NetSignalInfoExportTool.setWindowTitle(_translate("NetSignalInfoExportTool", "MainWindow"))
        self.Label_DatabaseFileInput.setText(_translate("NetSignalInfoExportTool", "Database File Input: "))
        self.pushButton_DatabaseFileInputSelect.setText(_translate("NetSignalInfoExportTool", "Select"))
        self.Label_OutputFolder.setText(_translate("NetSignalInfoExportTool", "Output File Folder: "))
        self.pushButton_OutputFolderSelect.setText(_translate("NetSignalInfoExportTool", "Select"))
        self.Label__ToolTitle.setText(_translate("NetSignalInfoExportTool", "Net Signal Info Export Tool"))
        self.pushButton_GenerateSignalInfoTable.setText(_translate("NetSignalInfoExportTool", "Generate  Signal  Info  Table"))

